import { BrainCircuit } from 'lucide-react'

export default function AiRecommendation({ text }) {
  return (
    <section className="rounded-panel border border-[#BBD3E8] border-l-[3px] border-l-brand bg-brand-soft shadow-[0_1px_2px_rgba(26,31,54,0.04)]">
      <header className="flex items-center gap-2 border-b border-[#CFDFEE] px-4 py-2.5">
        <BrainCircuit size={16} strokeWidth={1.75} className="text-brand" />
        <h2 className="text-[13px] font-semibold text-brand">AI Recommendation</h2>
      </header>

      <div className="px-4 py-3">
        <p className="text-[13px] leading-relaxed text-ink">{text}</p>
        <p className="mt-2.5 text-[12px] text-muted">
          Generated by SustainAir forecasting model · Confidence 87%
        </p>
      </div>
    </section>
  )
}
